-- View: vw_product_performance
-- Purpose: Encapsulates product-level revenue, unit volumes, and customer adoption metrics
-- Business Metric: Single source of truth for product sales and pricing performance
-- Updated: Automatically recalculated on query execution
-- Used By: Sales director dashboard, product analytics, inventory forecasting
--
-- Columns:
-- product_id: Unique product catalog identifier
-- product_name: Display name of the product
-- category: Product category classification
-- total_orders: Count of distinct orders containing this product
-- total_units_sold: Total quantity of units purchased
-- total_product_revenue: Gross revenue generated by product
-- avg_unit_price: Average price per unit across transactions
-- unique_buyers: Count of distinct customers purchasing product

CREATE VIEW IF NOT EXISTS vw_product_performance AS 
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    COUNT(DISTINCT oi.order_id) as total_orders,
    COALESCE(SUM(oi.quantity), 0) as total_units_sold,
    ROUND(COALESCE(SUM(oi.quantity * oi.unit_price), 0), 2) as total_product_revenue,
    ROUND(COALESCE(AVG(oi.unit_price), 0), 2) as avg_unit_price,
    COUNT(DISTINCT o.customer_id) as unique_buyers
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
LEFT JOIN orders o ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name, p.category;
